trigger:
  branches:
    include:
      - dev

variables:
  username: 'ujjalkrroy'
  password: 'igvpyeooggvprbp6aghwcnzuxuhxedbm3zlqea5beu4mgks2swca'

jobs:
  - job: CloneAndPush
    displayName: 'Clone and Push to Azure DevOps'
    pool:
      name: 'Self Pool'
    steps:
      - checkout: self

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'source'

      - script: |
          git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
          cd "D:\AzureDevops\AZ_Git\ClonedRepo"
          git remote rm origin
          git remote add azure https://$(username):$(password)@ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
          git remote -v
          git push azure --all
        displayName: 'Clone and Push'