---
trigger:
  branches:
    include:
      - dev
jobs:
   job: Clone And Push
   displayName: Clone from GitHub and Push to Azure DevOps
    pool:
     name: Self Pool
  steps:
    - checkout: self
    - script: |
        git clone https://github.com/UjjalKrRoy/AZ_Repo.git
      displayName: Clone from GitHub
    - script: >
        cd D:\AzureDevops\AZ_Git\Cloned Repo

        git remote add azure https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo

        git push azure --all
      displayName: Push to Azure DevOps
