trigger:
  branches:
    include:
      - dev

variables:
  GIT_TERMINAL_PROMPT: '1'
  azurepat: 'gfwph632epwwv3bdzevt27x5q6gelg7kcseph7eeymcrgvcfrcha'
#  username: 'ujjalkrroy'
#  password: 'igvpyeooggvprbp6aghwcnzuxuhxedbm3zlqea5beu4mgks2swca'

jobs:
  - job: CloneAndPush
    displayName: 'Clone and Push to Azure DevOps'
    pool:
      name: 'Self Pool'
    steps:
      - checkout: self

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'source'

      - script: |
          git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
          cd "D:\AzureDevops\AZ_Git\ClonedRepo"
          git remote rm origin
          git remote add https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
          git remote -v
          git push --all
        displayName: 'Clone and Push'