trigger:
  branches:
    include:
      - dev

jobs:
- job: CloneAndPush
  displayName: 'Clone from GitHub and Push to Azure DevOps'
  pool:
    name: 'Self Pool'
  steps:
  - checkout: self

  - script: |
      git clone https://github.com/UjjalKrRoy/AZ_Repo.git
    displayName: 'Clone from GitHub'

  - script: |
      cd D:\AzureDevops\AZ_Git\Cloned Repo
      git remote add https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
      git push --all
    displayName: 'Push to Azure DevOps'
