trigger:
  branches:
    include:
      - dev

#variables:
#  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
#  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    rd /S /Q "D:\AzureDevops\AZ_Git\ClonedRepo"
    del /S /Q "D:\AzureDevops\AZ_Git\ClonedRepo\*"
    git config --global credential.helper manager-core
    git config --global credential.modalprompt true
    cd D:\AzureDevops\AZ_Git\ClonedRepo
    git fetch https://github.com/UjjalKrRoy/AZ_Repo.git
  displayName: 'Pull code from GitHub'

- task: CmdLine@2
  inputs:
    script: |
      cd D:\AzureDevops\AZ_Git\ClonedRepo
      git remote rm origin
      git remote add azure https://ujjalkrroy:5bs6hchridmk6uevar6jcuqcg2zq2pk6ay3b57cf57ju67cbxfla@dev.azure.com/ujjalkrroy0295/MyProject/_git/My_Repo

- task: CmdLine@2
  inputs:
    script: |
      git remote -v
      git push -u azure --all