trigger:
  branches:
    include:
      - main

variables:
  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    git config --global credential.helper manager-core
    git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
  displayName: 'Pull code from GitHub'

- script: |
    cd "D:\AzureDevops\AZ_Git\ClonedRepo"
    git remote rm origin
  displayName: 'Intialize & Remove'
    
- script: |
    git config --global user.name "ujjalroy.indian@gmail.com"
    git config --global user.email "ujjalroy.indian@gmail.com"
    git remote add origin https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/My_Repo
    git remote -v
    git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push -u origin --all
  displayName: 'Push to Azure DevOps'