trigger:
  branches:
    include:
      - main

#variables:
#  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
#  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    rd /S /Q "D:\AzureDevops\AZ_Git\ClonedRepo"
    del /S /Q "D:\AzureDevops\AZ_Git\ClonedRepo\*"
    git config --global credential.helper manager-core
    git config --global credential.modalprompt true
    git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
  displayName: 'Pull code from GitHub'

- task: CmdLine@2
  inputs:
    script: |
      cd D:\AzureDevops\AZ_Git\ClonedRepo
      git remote add azure https://ujjalkrroy:zi3oeak3vwwuuiorugpxklq3dan7t2tvzcs5yor62oo3e3hojnqq@dev.azure.com/ujjalkrroy0295/MyProject/_git/My_Repo

- task: CmdLine@2
  inputs:
    script: |
      git remote -v
      git push -u azure --all