trigger:
  branches:
    include:
      - main

variables:
  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    git clone https://github.com/UjjalKrRoy/AZ_Repo.git
    cd <github-repo>
    git remote add azure https://dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
    git push azure --all --force
  displayName: 'Pull code from GitHub to Azure DevOps'
