trigger:
  branches:
    include:
      - main

variables:
  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    git remote rm azure
    git config --global credential.helper manager-core
    git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
    cd "D:\AzureDevops\AZ_Git\ClonedRepo"
    git remote add azure https://i6yobhzeb4azvb7zvioetnt6j6al3zrhfnjhm4yexy7vcqyvh3mq@ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
    git push azure --all
  displayName: 'Pull code from GitHub to Azure DevOps'
