trigger:
  branches:
    include:
      - main

variables:
  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git clone git@github.com:UjjalKrRoy/AZ_Repo.git
    cd AZ_Repo
    git remote add azure git@ssh.dev.azure.com:v3/ujjalkrroy0295/MyProject/AZ_Repo
    git push azure --all
  displayName: 'Pull code from GitHub to Azure DevOps'
