trigger:
  branches:
    include:
      - dev

jobs:
  - job: CloneAndPush
    displayName: 'Clone and Push to Azure DevOps'
    pool:
      name: 'Self Pool'

      - checkout: self

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'source'

      - script: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git clone https://github.com/UjjalKrRoy/AZ_Repo.git D:\AzureDevops\AZ_Git\ClonedRepo
          cd "D:\AzureDevops\AZ_Git\ClonedRepo"
          git remote add azure https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
          git push azure --all
        displayName: 'Clone and Push'