trigger:
    branches:
          include:
                  - dev  # Replace with your desired branch

          jobs:
            - job: CloneAndPush
                displayName: 'Clone from GitHub and Push to Azure DevOps'
                    pool: Self Pool
                        steps:
                            - checkout: self

                                - task: AzureCLI@2
                                      displayName: 'Azure CLI - Clone from GitHub'
                                            inputs:
                                                    scriptType: 'bash'
                                                            scriptLocation: 'inlineScript'
                                                                    inlineScript: |
                                                                              git clone https://github.com/UjjalKrRoy/AZ_Repo.git

                                                                                - task: AzureCLI@2
                                                                                      displayName: 'Azure CLI - Push to Azure DevOps'
                                                                                            inputs:
                                                                                                    scriptType: 'bash'
                                                                                                            scriptLocation: 'inlineScript'
                                                                                                                    inlineScript: |
                                                                                                                              cd AZ_Repo
                                                                                                                                      git remote add azure https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
                                                                                                                                              git push azure --all

