trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

#variables:
#  GIT_TERMINAL_PROMPT: '1'
#  azurepat: 'gfwph632epwwv3bdzevt27x5q6gelg7kcseph7eeymcrgvcfrcha'
#  username: 'ujjalkrroy'
#  password: 'igvpyeooggvprbp6aghwcnzuxuhxedbm3zlqea5beu4mgks2swca'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    git remote set-url origin https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo
    git push -u origin --all
  displayName: 'Transfer code to Azure DevOps'