trigger:
  branches:
    include:
      - main

variables:
  azure: 'https://ujjalkrroy0295@dev.azure.com/ujjalkrroy0295/MyProject/_git/AZ_Repo'
  git: 'https://github.com/UjjalKrRoy/AZ_Repo.git'

pr:
  branches:
    include:
      - '*'

pool:
  name: 'Self Pool'

steps:
- checkout: self

- script: |
    git remote rm origin
    git remote -v
    git remote set-url --push $(azure) $(git)
  displayName: 'Transfer code to Azure DevOps'