name: Auto Merge

on:
  push:
    branches:
      - feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Merge feature into dev
        run: git merge ${{ github.ref }} --no-ff --no-edit

      - name: Push changes
        run: git push origin HEAD

