name: Auto Merge

on:
  push:
    branches:
      - feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge feature into dev
          head: feature
          base: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: |
          curl -XPUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.create_pr.outputs.pull-request-number }}/merge"
