name: Automerge

on:
  push:
    branches:
      - feature

env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  MY_REPO: https://UjjalKrRoy:${{secrets.GITHUB_TOKEN}}@github.com/UjjalKrRoy/AzureProject.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: dev

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/username/master_repo.git

  # replace "master" with your master branch name
  MASTER_BRANCH: feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} /tmp
        cd /tmp
        git config user.name "Ujjal"
        git config user.email "ujjalroy.indian@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
