name: Auto-PR

on:
  push:
    branches:
      - feature

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature
          base: dev
          title: Demo for auto PR
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Auto-approved!"
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: repo-sync/github-sync@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: feature
          target_branch: dev
          method: merge

