name: Auto-PR

on:
  push:
    branches:
      - feature

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2
      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature
          base: dev
          title: Demo for auto PR
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Auto-approved!"
          number: ${{ steps.create_pr.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequestNumber = ${steps.create_pr.outputs.pull-request-number};
            const octokit = context.octokit;
            const { data: pullRequest } = await octokit.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber
            });
            if (pullRequest.mergeable) {
              await octokit.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequestNumber,
                merge_method: 'merge'
              });
              console.log('Pull request merged successfully.');
            } else {
              console.log('Pull request cannot be merged automatically.');
            }

