name: Auto Merge

on:
  push:
    branches:
      - feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge feature into dev
          head: feature
          base: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Pull Request
        id: wait_for_pr
        uses: srt32/wait-for-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ steps.create_pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          message: "Merging pull request automatically"
          delete-branch: true
