name: Automerge

on:
  push:
    branches:
      - feature

env:
  MY_REPO: https://UjjalKrRoy:${{secrets.GITHUB_TOKEN}}@github.com/UjjalKrRoy/AzureProject.git

  MY_BRANCH: dev

  MASTER_REPO: https://github.com/UjjalKrRoy/AzureProject.git

  MASTER_BRANCH: feature

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} /home/runner/work/tmp
        cd /home/runner/work/tmp
        git config user.name "Ujjal"
        git config user.email "ujjalroy.indian@gmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
