name: Auto-PR

on:
  push:
    branches:
      - feature

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: feature
          base: dev
          title: demo for auto pr
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ steps.create_pr.outputs.pull-request-number }}
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge_method: merge

