---
name: Auto-PR

on:
  push:
    branches:
      - feature
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: dev
          base: feature
          title: demo for auto pr
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
      - name: Approve Pull Request
          APPROVAL_RESPONSE=$(curl -sSL -X POST -H "${AUTH_HEADER}" -d '{"event": "APPROVE"}' "${API_URL}/${PR_NUMBER}/reviews")
          APPROVAL_ID=$(echo "${APPROVAL_RESPONSE}" | jq -r '.id')
      - name: Merge Pull request
          MERGE_RESPONSE=$(curl -sSL -X PUT -H "${AUTH_HEADER}" "${API_URL}/${PR_NUMBER}/merge")
          # Check if the merge was successful
          MERGE_STATUS=$(echo "${MERGE_RESPONSE}" | jq -r '.merged')

          if [[ "${MERGE_STATUS}" == "true" ]]; then
            echo "Pull request ${PR_NUMBER} was automatically created, approved, and merged."
          else
            echo "Failed to automatically create, approve, and merge pull request ${PR_NUMBER}."
          fi
